sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - sox
    - qt4-dev-tools
    - python-qt4
    - libqt4-declarative-folderlistmodel
    - libqt4-declarative-gestures
    - libqt4-declarative-particles 
    - libqt4-declarative-shaders
    - qt4-qmlviewer
    - qt4-doc unixodbc-dev
    - qt4-qtconfig
    - libsox-fmt-all 
    - python-qt4-dbg 
    - qt4-doc-html


# command to install dependencies
install:
  - pip install coveralls
  - pip install numpy
  - pip install pyyaml
  - pip install sox
  - python setup.py install 

# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=medley-de-bugger -v -w tests/

after_success:
    - coveralls
    - pip uninstall -y medley-de-bugger

after_failure:
    - pip uninstall -y medley-de-bugger