sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - sox
    - qt4-dev-tools
    - python-qt4


# command to install dependencies
install:
  - pip install coveralls
  - pip install numpy
  - pip install pyyaml
  - pip install sox
  - python setup.py install 

# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=medley-de-bugger -v -w tests/

after_success:
    - coveralls
    - pip uninstall -y medley-de-bugger

after_failure:
    - pip uninstall -y medley-de-bugger